name: Trigger APIdocs job in Jenkins

on:
  pull_request:
    branches: [ master ]
    types: [ closed ]
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: self-hosted
    if: github.event.pull_request.merged || github.event_name == 'workflow_dispatch'
    steps:
    - name: trigger single job
      uses: appleboy/jenkins-action@master
      with:
        url: "https://jenkins.internal.moesif.com"
        user: "moesif-ci-cd"
        token: ${{ secrets.TOKEN }}
        job: "Static site deployment - APIdocs"